### PR TITLE
Fix compiler warnings and add CODEOWNERS

### PR DESCRIPTION
**Pull request by sorpaas**
* Replace `var` to `<type>`, because the former is deprecated.
* Add CODEOWNERS

### CODE REVIEW

**Comment by sorpaas** [comment]
The buildkite failure looks indeed like it is the case -- `Badge::meta` is not properly deleted so this might be a low-priority security issue.

**Comment by kirushik** [comment]
@sorpaas Looks like (at least at the moment) we're not relying on any `meta` values anywhere in the code.
This means the in case of "mapping hijacking" (creating the new badge with the same `id`) the meta from the old record will be inherited by the new one.

This might lead to the "read meta after deletion" bug — but is not a security concern, as long as:

 1. We only add badges to the array with `push`, thus effectively never reusing the same `id` twice.
 2. (a little bit more far-fetched) We don't rely on anything in those `meta` fields in the code, so it's not a subject for "mapping hijacking", when one legitimate cell owner sets the mapping, and then after the deletion of the record the next user is inheriting all the mappings somehow, adding them extended permissions or whatnot.

Still, maybe the "safe-deletion" (with a boolean flag `deleted` on the record) will be a safer alternative to the `delete` we have now? Like @andresilva did for [SimpleOperations.sol](https://github.com/parity-contracts/auto-updater/blob/5496aa730b242d4ffbd2846497718068d7062bdf/contracts/SimpleOperations.sol#L273).

**Comment by sorpaas** [comment]
Tried a version using the safe deletion method:

* Changed all current `if return` modifier to use `require`. This is both more clearer for the source code and contract user -- we're already throwing errors for out of bound indexes.
* Added deleted flag in `Badge`, and change `badgeCount` to be a variable to store the actual count.

**Review by andresilva — APPROVED** [review]
LGTM!

**Comment by andresilva** [comment]
I'll write a test spec for this.

**Review by kirushik — APPROVED** [review]

**Pull request merged**
